[build.environment]
HUGO_VERSION = "0.129.0"
TZ = "America/Denver"

[build]
base = "resume"
publish = "public"
command = "hugo --gc --minify"

# Rewrite a path
[[redirects]]
from = "/resume"
to = "/"
status = 200
